### ISSUE TITLE
Entry Fee?

### ISSUE THREAD

**Issue by ghost** [uxebu/jsCodeRetreat#2]
Hey uxebu, 

Thanks for putting this on in Munich this February!
Will there be a fee / recommended donation for the participants attending?
I am really looking forward to it.

// Francis

**Comment by wolframkriesing** [comment]
Hi Francis, 

there will be no entry fee, dont worry.
Just come, enjoy and practice along :)
Everything will be sponsored.

Best

Wolfram

**Comment by ghost** [comment]
Awesome! Thanks much Wolfram.
