### ISSUE TITLE
Problem showing joined attendees 

### ISSUE THREAD

**Issue by borillo** [uxebu/jsCodeRetreat#6]
Hi @wolframkriesing. You are showing who has joined the event in lanyard, but this list is not beeing showed in the VLC page:

http://jscoderetreat.com/city/es-valencia.html

Do you know what is happening?

**Comment by wolframkriesing** [comment]
@borillo did u claim the event? I did that and got the "ownership" a couple days later, and only then i was able to embed it in the page

**Comment by borillo** [comment]
I think that i would be great that @flype could complet the ownership ... :)

Thx!!!

**Comment by otorras** [comment]
After getting the ownership you have to go to "Manage this event" and check the "Embeddable speaker/attendee widget" option

**Comment by wolframkriesing** [comment]
got any input on the instructions I put here
http://jscoderetreat.com/2/city/new.html#lanyrd  ?

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Come and practice - http://jscoderetreat.com

Wolfram Kriesing
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595
